baseURL = "https://remast.github.io"
languageCode = "de-de"
title = "Jan Stamer"
author = "Jan Stamer"
theme = "remast"
[menu]
  [[menu.main]]
    name = "Vorträge"
    pre = "talks"
    url = "/talks/"
    weight = 1
  [[menu.main]]
    name = "Artikel"
    pre = "articles"
    url = "/articles/"
    weight = 2
  [[menu.main]]
    name = "Blog"
    pre = "Blog"
    url = "/posts/"
    weight = 3
[markup.goldmark.renderer]
  unsafe= true
[params]
  twitter = "jsTamer21k"
  author = "Jan Stamer"
  description = "Jan Stamer - Coder und Creator von nachhaltigen Lösungen mit Java und Go. Teilt sein Wissen als Speaker und Autor."