baseURL = "https://remast.github.io"
languageCode = "de-de"
title = "Jan Stamer"
author = "Jan Stamer"
theme = "remast"
[menu]
  [[menu.main]]
    name = "home"
    pre = "home"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "posts"
    pre = "posts"
    url = "/posts/"
    weight = 2
[markup.goldmark.renderer]
  unsafe= true
[params]
  twitter = "jsTamer21k"
  author = "Jan Stamer"
  description = "Jan Stamer - Coder und Creator von nachhaltigen Lösungen mit Java und Go. Teilt sein Wissen als Speaker und Autor."